"""Render the daily lead set to CSV and a self-contained HTML report."""

from __future__ import annotations

import csv
import html
from datetime import date
from pathlib import Path
from typing import Sequence

from .models import Lead

CSV_COLUMNS = [
    "kind",
    "source",
    "name",
    "age",
    "address",
    "city",
    "zip_code",
    "pt_number",
    "sale_date",
    "original_balance",
    "death_date",
    "parcel_account",
    "parcel_owner_name",
    "parcel_actual_value",
    "parcel_site_address",
    "detail_url",
    "first_seen",
    "fingerprint",
]


def write_csv(leads: Sequence[Lead], path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=CSV_COLUMNS, extrasaction="ignore")
        writer.writeheader()
        for lead in leads:
            writer.writerow(lead.to_row())
    return path


def _fmt_money(v) -> str:
    try:
        return f"${float(v):,.0f}" if v is not None else ""
    except (TypeError, ValueError):
        return ""


def render_html(leads: Sequence[Lead], run_date: date | None = None) -> str:
    run_date = run_date or date.today()
    foreclosures = [x for x in leads if x.kind == "foreclosure"]
    obituaries = [x for x in leads if x.kind == "obituary"]

    def rows(items: Sequence[Lead]) -> str:
        out = []
        for x in items:
            prop = x.matched_property
            out.append(
                "<tr>"
                f"<td>{_esc(x.name)}</td>"
                f"<td>{_esc(x.age)}</td>"
                f"<td>{_esc(x.address or (prop.site_address if prop else ''))}</td>"
                f"<td>{_esc(x.sale_date or x.death_date or '')}</td>"
                f"<td>{_esc(prop.owner_name if prop else '')}</td>"
                f"<td>{_fmt_money(prop.actual_value if prop else None)}</td>"
                f"<td>{_link(x.detail_url)}</td>"
                "</tr>"
            )
        return "\n".join(out) or '<tr><td colspan="7"><em>None today.</em></td></tr>'

    return f"""<!doctype html>
<html><head><meta charset="utf-8">
<title>Castle Rock Leads — {run_date}</title>
<style>
 body {{ font-family: -apple-system, Segoe UI, Roboto, sans-serif; margin: 2rem; color:#1a1a1a; }}
 h1 {{ font-size: 1.4rem; }} h2 {{ margin-top: 2rem; font-size: 1.1rem; }}
 table {{ border-collapse: collapse; width: 100%; font-size: 0.9rem; }}
 th, td {{ border: 1px solid #ddd; padding: 6px 8px; text-align: left; vertical-align: top; }}
 th {{ background:#f4f4f4; }} tr:nth-child(even) {{ background:#fafafa; }}
 .meta {{ color:#666; font-size:0.85rem; }}
</style></head><body>
<h1>Castle Rock daily leads — {run_date}</h1>
<p class="meta">{len(foreclosures)} new foreclosure(s) · {len(obituaries)} new obituary lead(s).
Public records only. Cross-referenced against Douglas County parcel data.</p>

<h2>Foreclosures (Douglas County Public Trustee)</h2>
<table><thead><tr>
<th>Grantor/Owner</th><th>Age</th><th>Address</th><th>Sale date</th>
<th>Assessor owner</th><th>Actual value</th><th>Source</th>
</tr></thead><tbody>
{rows(foreclosures)}
</tbody></table>

<h2>Obituaries (possible estate sales)</h2>
<table><thead><tr>
<th>Name</th><th>Age</th><th>Matched property</th><th>Death date</th>
<th>Assessor owner</th><th>Actual value</th><th>Source</th>
</tr></thead><tbody>
{rows(obituaries)}
</tbody></table>

<p class="meta">Generated by castlerock-leads. Contact leads respectfully and in
compliance with Do-Not-Call and applicable regulations.</p>
</body></html>"""


def write_html(leads: Sequence[Lead], path: Path, run_date: date | None = None) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_html(leads, run_date), encoding="utf-8")
    return path


def _esc(v) -> str:
    return html.escape(str(v)) if v not in (None, "") else ""


def _link(url) -> str:
    if not url:
        return ""
    safe = html.escape(str(url), quote=True)
    return f'<a href="{safe}">link</a>'
